amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_link"
    global_frame_id: "map"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # ✅ FIXED
    odom_frame_id: "odom"
    scan_topic: "scan"
    update_min_d: 0.25
    update_min_a: 0.2
    max_particles: 500
    min_particles: 200

collision_monitor:
  ros__parameters:
    use_sim_time: false
    enabled: false  # ✅ RECOMMENDED: disable it for now
